### ISSUE TITLE
Create leads from pre-approval

### ISSUE THREAD

**Issue by sam-lippert** [drivly/pre-approval#5]
Mary Garwood submitted a preapproval but is not a lead in airtable.
Create leads if they do not exist: https://github.com/drivly/pre-approval/blob/73f106977431701ef5f573ce497145740f076596/src/app/api/pre-approval/route.ts#L29C7-L29C12

[Slack Message](https://drivly.slack.com/archives/C05EJ23SN2W/p1692823965510529)

**Comment by crisner1978** [comment]
- creating lead if doesn't exist done
